# -*- coding: utf-8 -*-
""" 
Algoritmo Genetico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sh36ypERToBjP0G7-zaLcMxpoXF4HeKN
Analisis ticket hospital 
Camilo Prieto
Carlos Jimenez
"""
from typing import List, Tuple
import random
import matplotlib.pyplot as plt

# ----------------------------
# CONFIGURACIÓN HOSPITALARIA
# ----------------------------

NUM_CAMAS = 5

TURNOS = ["mañana", "tarde", "noche"]

COSTOS_TURNO = {
    "mañana": 100,
    "tarde": 120,
    "noche": 150
}

pacientes = [

    {
        "id": 1,
        "tipo": "convulsion",
        "prioridad": 1,
        "peso_penalizacion": 10,
        "tiempo_espera_max": 5,
        "tiempo_espera": 4
    },

    {
        "id": 2,
        "tipo": "dolor_abdominal",
        "prioridad": 2,
        "peso_penalizacion": 5,
        "tiempo_espera_max": 20,
        "tiempo_espera": 15
    },

    {
        "id": 3,
        "tipo": "sutura",
        "prioridad": 3,
        "peso_penalizacion": 1,
        "tiempo_espera_max": 60,
        "tiempo_espera": 40
    }
]

pacientes_dict = {p["id"]: p for p in pacientes}

# ---------- Problema: OneMax ----------
def fitness(individual):

    penalizacion_total = 0
    camas_ocupadas = set()
    contador_turnos = {}

    for asignacion in individual:

        paciente_id, cama, turno = asignacion

        paciente = pacientes_dict[paciente_id]

        tiempo_espera = paciente["tiempo_espera"]

        penalizacion = (
            (tiempo_espera / paciente["tiempo_espera_max"]) *
            paciente["peso_penalizacion"]
        )

        penalizacion_total += penalizacion

        costo_operativo = COSTOS_TURNO[turno]
        penalizacion_total += costo_operativo * 0.5

        # Penalizar camas repetidas
        if (cama, turno) in camas_ocupadas:
            penalizacion_total += 1000

        camas_ocupadas.add((cama, turno))

        # conteo de turnos
        contador_turnos = {}
        contador_turnos[turno] = contador_turnos.get(turno, 0) + 1

    # penalización por saturación
    
    for turno, cantidad in contador_turnos.items():
        if cantidad > 2:
            penalizacion_total += 200

    return -penalizacion_total




# ---------- Operadores genéticos ----------
def random_individual():

    individual = []

    for paciente in pacientes:

        cama = random.randint(1, NUM_CAMAS)

        turno = random.choice(TURNOS)

        individual.append(
            (paciente["id"], cama, turno)
        )

    return individual



def init_population(pop_size):

    return [random_individual() for _ in range(pop_size)]



def tournament_selection(population, k):
    """Selecciona 1 padre mediante torneo de tamaño k."""
    contenders = random.sample(population, k)
    return max(contenders, key=fitness)



def one_point_crossover(p1, p2, pc):

    if random.random() >= pc:
        return p1[:], p2[:]

    point = random.randint(1, len(p1) - 1)

    child1 = p1[:point] + p2[point:]
    child2 = p2[:point] + p1[point:]

    return child1, child2



def mutation(individual, pm):

    mutated = []

    for paciente_id, cama, turno in individual:

        nueva_cama = cama
        nuevo_turno = turno

        # Mutar cama
        if random.random() < pm:
            nueva_cama = random.randint(1, NUM_CAMAS)

        # Mutar turno
        if random.random() < pm:
            nuevo_turno = random.choice(TURNOS)

        mutated.append(
            (paciente_id, nueva_cama, nuevo_turno)
        )

    return mutated



# ---------- Bucle evolutivo ----------
def genetic_algorithm(
    pop_size: int = 60,
    generations: int = 350,
    tournament_k: int = 3,
    pc: float = 0.9,
    pm: float = 0.01,
    elitism: int = 1,
    seed: int = 42,
    verbose_every: int = 10
):
    random.seed(seed)

    population = init_population(pop_size)

    best_overall = None
    best_fit_overall = float("-inf")

    # HISTÓRICOS
    best_fitness_history = []
    avg_fitness_history = []
    worst_fitness_history = []

    for gen in range(1, generations + 1):
        population.sort(key=fitness, reverse=True)

        fitness_values = [fitness(ind) for ind in population]

        # Guardar estadísticas
        best_fitness_history.append(fitness_values[0])
        avg_fitness_history.append(sum(fitness_values) / len(fitness_values))
        worst_fitness_history.append(fitness_values[-1])

        # Mejor global
        if fitness(population[0]) > best_fit_overall:
            best_overall = population[0][:]
            best_fit_overall = fitness(best_overall)

        if verbose_every and gen % verbose_every == 0:
            print(f"Gen {gen:4d} | Mejor fitness: {fitness_values[0]}")

        new_population = [population[i][:] for i in range(elitism)]

        while len(new_population) < pop_size:
            p1 = tournament_selection(population, tournament_k)
            p2 = tournament_selection(population, tournament_k)

            c1, c2 = one_point_crossover(p1, p2, pc)
            c1 = mutation(c1, pm)
            c2 = mutation(c2, pm)

            new_population.append(c1)
            if len(new_population) < pop_size:
                new_population.append(c2)

        population = new_population

    return (
        best_overall,
        best_fit_overall,
        best_fitness_history,
        avg_fitness_history,
        worst_fitness_history
    )



# ---------- Ejecutar ----------
if __name__ == "__main__":
    
    best, score, best_hist, avg_hist, worst_hist = genetic_algorithm(
    pop_size=100,
    generations=200,
    tournament_k=4,
    pc=0.9,
    pm=0.1,
    elitism=2,
    seed=7,
    verbose_every=10
    )

    print("\nMejor individuo:", best)
    print("Fitness:", score)
    print("\n--- ESTADÍSTICAS FINALES ---")

    total_espera = 0
    total_costos = 0

    for paciente_id, cama, turno in best:

        paciente = next(
            p for p in pacientes
            if p["id"] == paciente_id
        )

        espera = paciente["tiempo_espera"]

        costo = COSTOS_TURNO[turno]

        total_espera += espera
        total_costos += costo

        print(
            f"Paciente {paciente_id} "
            f"| Tipo: {paciente['tipo']} "
            f"| Cama: {cama} "
            f"| Turno: {turno} "
            f"| Espera: {espera} min "
            f"| Costo: ${costo}"
        )

    print("\nTiempo promedio de espera:",
        total_espera / len(best),
        "min")

    print("Costo operativo total:",
        total_costos)
    
    # ----------------------------
    # GRÁFICA 1: EVOLUCIÓN
    # ----------------------------
    plt.figure(figsize=(10, 6))

    plt.plot(best_hist, label="Mejor Fitness", linewidth=2)
    plt.plot(avg_hist, label="Fitness Promedio")
    plt.plot(worst_hist, label="Peor Fitness", linestyle="--")

    plt.title("Evolución del Algoritmo Genético")
    plt.xlabel("Generaciones")
    plt.ylabel("Fitness")
    plt.legend()
    plt.grid()

    plt.show()

    # ----------------------------
    # GRÁFICA 2: PACIENTES
    # ----------------------------
    pacientes_ids = []
    esperas = []
    costos = []

    for paciente_id, cama, turno in best:
        paciente = next(p for p in pacientes if p["id"] == paciente_id)

        pacientes_ids.append(f"P{paciente_id}")
        esperas.append(paciente["tiempo_espera"])
        costos.append(COSTOS_TURNO[turno])

    x = range(len(pacientes_ids))

    plt.figure(figsize=(10,5))

    # Mejora visual (lado a lado)
    plt.bar([i - 0.2 for i in x], esperas, width=0.4, label="Tiempo de espera")
    plt.bar([i + 0.2 for i in x], costos, width=0.4, label="Costo")

    plt.xticks(x, pacientes_ids)
    plt.title("Comparación por paciente")
    plt.xlabel("Pacientes")
    plt.ylabel("Valores")
    plt.legend()
    plt.grid()

    plt.show()

